version: '3.8'

services:
  postgres:
    image: postgres:14.2
    environment:
      POSTGRES_USER: my_user
      POSTGRES_PASSWORD: my_password
      POSTGRES_DB: invoicing
    ports:
      - "5500:5432"
