version: '3.8'

services:
  postgres:
    image: postgres:14.2
    environment:
      POSTGRES_USER: invoicing_admin
      POSTGRES_PASSWORD: my_password
      POSTGRES_DB: invoicing
    volumes:
      - ./scripts/initdb-local-docker:/docker-entrypoint-initdb.d
    ports:
      - "5500:5432"
